remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: The OutN Project
description: An Amazing Self-hostable FOSS Pokémon assist and more bot for the discord game "Poketwo".

show_downloads: true